### ISSUE TITLE
Wflow hangs on collecting commit information

### ISSUE THREAD

**Issue by Siilwyn** [phishy/wflow#18]
I get parsing errors on existing (working on GitHub) workflows so I tried out wflow with a hello world workflow file which results into the tool hanging forever on `Collecting commit information from .git`.

To reproduce:
`wflow --file .github/workflows/hello.yml`

```yaml
uses: actions/hello-world-javascript-action@master
with:
  who-to-greet: 'Mona the Octocat'
```
